//: Playground - noun: a place where people can play

import UIKit

var str = "Hello, playground"

//Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var fiboArray :[UIntMax] = [0, 1]

func calculateFiboNumber(array: [UIntMax]) -> UIntMax {
    var newArray = array
    return newArray[newArray.count-1] + newArray[newArray.count-2]
}


func addNextFiboNumber(array: [UIntMax]) -> (Int){
    var counter = 0
    var sum: UIntMax = 0
    var newArray = array
    while counter < 32 {
        let fiboNumber = calculateFiboNumber(array: newArray)
        if fiboNumber < 4000000{
        print(fiboNumber)
        sum += fiboNumber
        newArray.append(fiboNumber)
        counter+=1
        }
    }
    return (Int)(sum)
}

var newSum = addNextFiboNumber(array: fiboArray)
print(newSum)






